### ISSUE TITLE
Issue loading .dll on MacOS

### ISSUE THREAD

**Issue by DenisCarriere** [extropiescom/Sabre#1]
I'm on MacOS and seems like `ffi` is trying to load `EWallet.dll.dylib`

@chesterliliang Am I missing that file or is this file supposed to be compiled on run time?

```
$ node eos/wallet/eos.js
/Users/mac/Github/Sabre/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: dlopen(/Users/mac/Github/Sabre/eos/dllimport/EWallet.dll.dylib, 2): image not found
```

I've never used `ffi` before to load C++ libraries, I'll dig into this deeper on my side

**Comment by eshangui** [comment]
Please try the newly committed code and library, the former code does only support Windows OS.

P.S: this code is a simple demonstration, as usually dynamic libraries are named with a 'lib' prefix on unix-like systems, so if you'd like to follow the system naming style, you may use the code below and rename the dynamic library file EWallet.dylib to libEWallet.dylib :

```javascript
const os = require('os') 
const DLLAPI = ffi.Library(path.resolve(process.env.LIBDIR, os.platform() === 'win32' ? 'EWallet' : 'libEWallet'), {
    ......
};
```

**Comment by DenisCarriere** [comment]
👍 Thanks the latest code works with MacOS, well it loads correctly now
